version: '3'

volumes:
  db_data: {}

services:
  backend:
    image: 127.0.0.1:5000/crawler
    build:
      context: .
      dockerfile: compose/backend/Dockerfile
    env_file:
      - .env
    command: gunicorn main:app -b 0.0.0.0:8080 -w 4 -k uvicorn.workers.UvicornWorker
    volumes:
      - ./crawler:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env

  nginx:
    image: 127.0.0.1:5000/nginx
    build:
      context: .
      dockerfile: compose/nginx/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - backend